// <auto-generated />
using System;
using GymCoach.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymCoach.Api.Migrations
{
    [DbContext(typeof(GymCoachDbContext))]
    [Migration("20260110223323_AddPersonalRecords")]
    partial class AddPersonalRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymCoach.Api.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "body",
                            Name = "Bodyweight"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "dumbbell",
                            Name = "Dumbbells"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "barbell",
                            Name = "Barbell"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "pullup",
                            Name = "Pull-up Bar"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "cable",
                            Name = "Cables"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "machine",
                            Name = "Machines"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "kettlebell",
                            Name = "Kettlebell"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "bench",
                            Name = "Bench"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "band",
                            Name = "Resistance Bands"
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultRole")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrimaryMuscleGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryMuscleGroupId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultRole = 2,
                            Description = "Classic bodyweight chest exercise",
                            Name = "Push-ups",
                            PrimaryMuscleGroupId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            DefaultRole = 2,
                            Description = "Flat bench press with dumbbells",
                            Name = "Dumbbell Bench Press",
                            PrimaryMuscleGroupId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            DefaultRole = 2,
                            Description = "Incline bench press with dumbbells",
                            Name = "Dumbbell Incline Press",
                            PrimaryMuscleGroupId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            DefaultRole = 3,
                            Description = "Chest isolation exercise",
                            Name = "Dumbbell Flyes",
                            PrimaryMuscleGroupId = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            DefaultRole = 1,
                            Description = "Flat bench press with barbell",
                            Name = "Barbell Bench Press",
                            PrimaryMuscleGroupId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            DefaultRole = 1,
                            Description = "Bodyweight back exercise",
                            Name = "Pull-ups",
                            PrimaryMuscleGroupId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            DefaultRole = 2,
                            Description = "Single arm dumbbell row",
                            Name = "Dumbbell Rows",
                            PrimaryMuscleGroupId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            DefaultRole = 1,
                            Description = "Bent over barbell row",
                            Name = "Barbell Rows",
                            PrimaryMuscleGroupId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            DefaultRole = 2,
                            Description = "Cable lat pulldown",
                            Name = "Lat Pulldown",
                            PrimaryMuscleGroupId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            DefaultRole = 2,
                            Description = "Cable row for back thickness",
                            Name = "Seated Cable Row",
                            PrimaryMuscleGroupId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            DefaultRole = 2,
                            Description = "Overhead press with dumbbells",
                            Name = "Dumbbell Shoulder Press",
                            PrimaryMuscleGroupId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            DefaultRole = 3,
                            Description = "Side deltoid isolation",
                            Name = "Dumbbell Lateral Raises",
                            PrimaryMuscleGroupId = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = 13,
                            DefaultRole = 3,
                            Description = "Front deltoid isolation",
                            Name = "Dumbbell Front Raises",
                            PrimaryMuscleGroupId = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            DefaultRole = 3,
                            Description = "Rear deltoid and rotator cuff",
                            Name = "Face Pulls",
                            PrimaryMuscleGroupId = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            DefaultRole = 1,
                            Description = "Standing overhead press",
                            Name = "Barbell Overhead Press",
                            PrimaryMuscleGroupId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            DefaultRole = 3,
                            Description = "Standing dumbbell curls",
                            Name = "Dumbbell Bicep Curls",
                            PrimaryMuscleGroupId = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            DefaultRole = 3,
                            Description = "Neutral grip dumbbell curls",
                            Name = "Hammer Curls",
                            PrimaryMuscleGroupId = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = 18,
                            DefaultRole = 2,
                            Description = "Standing barbell curls",
                            Name = "Barbell Curls",
                            PrimaryMuscleGroupId = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = 19,
                            DefaultRole = 3,
                            Description = "Cable bicep curls",
                            Name = "Cable Curls",
                            PrimaryMuscleGroupId = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = 20,
                            DefaultRole = 1,
                            Description = "Underhand pull-ups",
                            Name = "Chin-ups",
                            PrimaryMuscleGroupId = 4,
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            DefaultRole = 2,
                            Description = "Bodyweight tricep exercise",
                            Name = "Tricep Dips",
                            PrimaryMuscleGroupId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            DefaultRole = 3,
                            Description = "Overhead tricep extension",
                            Name = "Dumbbell Tricep Extension",
                            PrimaryMuscleGroupId = 5,
                            Type = 2
                        },
                        new
                        {
                            Id = 23,
                            DefaultRole = 3,
                            Description = "Cable pushdowns",
                            Name = "Tricep Pushdowns",
                            PrimaryMuscleGroupId = 5,
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            DefaultRole = 2,
                            Description = "Narrow grip bench press",
                            Name = "Close Grip Bench Press",
                            PrimaryMuscleGroupId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            DefaultRole = 2,
                            Description = "Narrow push-ups for triceps",
                            Name = "Diamond Push-ups",
                            PrimaryMuscleGroupId = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            DefaultRole = 2,
                            Description = "Basic bodyweight squat",
                            Name = "Bodyweight Squats",
                            PrimaryMuscleGroupId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            DefaultRole = 2,
                            Description = "Dumbbell held at chest",
                            Name = "Goblet Squats",
                            PrimaryMuscleGroupId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 28,
                            DefaultRole = 1,
                            Description = "Back squats with barbell",
                            Name = "Barbell Squats",
                            PrimaryMuscleGroupId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            DefaultRole = 2,
                            Description = "Machine leg press",
                            Name = "Leg Press",
                            PrimaryMuscleGroupId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 30,
                            DefaultRole = 2,
                            Description = "Walking or stationary lunges",
                            Name = "Lunges",
                            PrimaryMuscleGroupId = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = 31,
                            DefaultRole = 1,
                            Description = "Dumbbell or barbell RDL",
                            Name = "Romanian Deadlift",
                            PrimaryMuscleGroupId = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 32,
                            DefaultRole = 3,
                            Description = "Machine leg curls",
                            Name = "Leg Curls",
                            PrimaryMuscleGroupId = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 33,
                            DefaultRole = 2,
                            Description = "Barbell good mornings",
                            Name = "Good Mornings",
                            PrimaryMuscleGroupId = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = 34,
                            DefaultRole = 3,
                            Description = "Bodyweight hamstring exercise",
                            Name = "Nordic Curls",
                            PrimaryMuscleGroupId = 7,
                            Type = 2
                        },
                        new
                        {
                            Id = 35,
                            DefaultRole = 1,
                            Description = "Barbell or dumbbell hip thrusts",
                            Name = "Hip Thrusts",
                            PrimaryMuscleGroupId = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            DefaultRole = 3,
                            Description = "Bodyweight glute bridges",
                            Name = "Glute Bridges",
                            PrimaryMuscleGroupId = 8,
                            Type = 2
                        },
                        new
                        {
                            Id = 37,
                            DefaultRole = 2,
                            Description = "Rear foot elevated split squats",
                            Name = "Bulgarian Split Squats",
                            PrimaryMuscleGroupId = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = 38,
                            DefaultRole = 3,
                            Description = "Dumbbell calf raises",
                            Name = "Standing Calf Raises",
                            PrimaryMuscleGroupId = 9,
                            Type = 2
                        },
                        new
                        {
                            Id = 39,
                            DefaultRole = 3,
                            Description = "Machine seated calf raises",
                            Name = "Seated Calf Raises",
                            PrimaryMuscleGroupId = 9,
                            Type = 2
                        },
                        new
                        {
                            Id = 40,
                            DefaultRole = 3,
                            Description = "Isometric core hold",
                            Name = "Plank",
                            PrimaryMuscleGroupId = 10,
                            Type = 2
                        },
                        new
                        {
                            Id = 41,
                            DefaultRole = 3,
                            Description = "Basic abdominal crunches",
                            Name = "Crunches",
                            PrimaryMuscleGroupId = 10,
                            Type = 2
                        },
                        new
                        {
                            Id = 42,
                            DefaultRole = 2,
                            Description = "Hanging from bar leg raises",
                            Name = "Hanging Leg Raises",
                            PrimaryMuscleGroupId = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = 43,
                            DefaultRole = 3,
                            Description = "Rotational core exercise",
                            Name = "Russian Twists",
                            PrimaryMuscleGroupId = 10,
                            Type = 2
                        },
                        new
                        {
                            Id = 44,
                            DefaultRole = 3,
                            Description = "Anti-rotation core exercise",
                            Name = "Dead Bug",
                            PrimaryMuscleGroupId = 10,
                            Type = 2
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.ExerciseEquipment", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.HasKey("ExerciseId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ExerciseEquipment");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            EquipmentId = 1
                        },
                        new
                        {
                            ExerciseId = 6,
                            EquipmentId = 4
                        },
                        new
                        {
                            ExerciseId = 20,
                            EquipmentId = 4
                        },
                        new
                        {
                            ExerciseId = 21,
                            EquipmentId = 1
                        },
                        new
                        {
                            ExerciseId = 25,
                            EquipmentId = 1
                        },
                        new
                        {
                            ExerciseId = 26,
                            EquipmentId = 1
                        },
                        new
                        {
                            ExerciseId = 34,
                            EquipmentId = 1
                        },
                        new
                        {
                            ExerciseId = 36,
                            EquipmentId = 1
                        },
                        new
                        {
                            ExerciseId = 40,
                            EquipmentId = 1
                        },
                        new
                        {
                            ExerciseId = 41,
                            EquipmentId = 1
                        },
                        new
                        {
                            ExerciseId = 44,
                            EquipmentId = 1
                        },
                        new
                        {
                            ExerciseId = 2,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 2,
                            EquipmentId = 8
                        },
                        new
                        {
                            ExerciseId = 3,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 3,
                            EquipmentId = 8
                        },
                        new
                        {
                            ExerciseId = 4,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 4,
                            EquipmentId = 8
                        },
                        new
                        {
                            ExerciseId = 7,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 11,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 12,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 13,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 16,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 17,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 22,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 27,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 30,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 31,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 35,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 37,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 38,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 43,
                            EquipmentId = 2
                        },
                        new
                        {
                            ExerciseId = 5,
                            EquipmentId = 3
                        },
                        new
                        {
                            ExerciseId = 5,
                            EquipmentId = 8
                        },
                        new
                        {
                            ExerciseId = 8,
                            EquipmentId = 3
                        },
                        new
                        {
                            ExerciseId = 15,
                            EquipmentId = 3
                        },
                        new
                        {
                            ExerciseId = 18,
                            EquipmentId = 3
                        },
                        new
                        {
                            ExerciseId = 24,
                            EquipmentId = 3
                        },
                        new
                        {
                            ExerciseId = 24,
                            EquipmentId = 8
                        },
                        new
                        {
                            ExerciseId = 28,
                            EquipmentId = 3
                        },
                        new
                        {
                            ExerciseId = 33,
                            EquipmentId = 3
                        },
                        new
                        {
                            ExerciseId = 35,
                            EquipmentId = 3
                        },
                        new
                        {
                            ExerciseId = 9,
                            EquipmentId = 5
                        },
                        new
                        {
                            ExerciseId = 10,
                            EquipmentId = 5
                        },
                        new
                        {
                            ExerciseId = 14,
                            EquipmentId = 5
                        },
                        new
                        {
                            ExerciseId = 19,
                            EquipmentId = 5
                        },
                        new
                        {
                            ExerciseId = 23,
                            EquipmentId = 5
                        },
                        new
                        {
                            ExerciseId = 29,
                            EquipmentId = 6
                        },
                        new
                        {
                            ExerciseId = 32,
                            EquipmentId = 6
                        },
                        new
                        {
                            ExerciseId = 39,
                            EquipmentId = 6
                        },
                        new
                        {
                            ExerciseId = 42,
                            EquipmentId = 4
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.ExerciseSecondaryMuscle", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("integer");

                    b.HasKey("ExerciseId", "MuscleGroupId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("ExerciseSecondaryMuscle");

                    b.HasData(
                        new
                        {
                            ExerciseId = 1,
                            MuscleGroupId = 5
                        },
                        new
                        {
                            ExerciseId = 1,
                            MuscleGroupId = 3
                        },
                        new
                        {
                            ExerciseId = 2,
                            MuscleGroupId = 5
                        },
                        new
                        {
                            ExerciseId = 3,
                            MuscleGroupId = 5
                        },
                        new
                        {
                            ExerciseId = 5,
                            MuscleGroupId = 5
                        },
                        new
                        {
                            ExerciseId = 6,
                            MuscleGroupId = 4
                        },
                        new
                        {
                            ExerciseId = 7,
                            MuscleGroupId = 4
                        },
                        new
                        {
                            ExerciseId = 8,
                            MuscleGroupId = 4
                        },
                        new
                        {
                            ExerciseId = 10,
                            MuscleGroupId = 4
                        },
                        new
                        {
                            ExerciseId = 11,
                            MuscleGroupId = 5
                        },
                        new
                        {
                            ExerciseId = 15,
                            MuscleGroupId = 5
                        },
                        new
                        {
                            ExerciseId = 20,
                            MuscleGroupId = 2
                        },
                        new
                        {
                            ExerciseId = 26,
                            MuscleGroupId = 8
                        },
                        new
                        {
                            ExerciseId = 27,
                            MuscleGroupId = 8
                        },
                        new
                        {
                            ExerciseId = 28,
                            MuscleGroupId = 8
                        },
                        new
                        {
                            ExerciseId = 28,
                            MuscleGroupId = 7
                        },
                        new
                        {
                            ExerciseId = 30,
                            MuscleGroupId = 8
                        },
                        new
                        {
                            ExerciseId = 31,
                            MuscleGroupId = 8
                        },
                        new
                        {
                            ExerciseId = 37,
                            MuscleGroupId = 6
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.ExerciseSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("ActualReps")
                        .HasColumnType("integer");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("RepSchemeId")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TargetReps")
                        .HasColumnType("integer");

                    b.Property<int>("UserExerciseLogId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("RepSchemeId");

                    b.HasIndex("UserExerciseLogId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("GymCoach.Api.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Back"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shoulders"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Triceps"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Quadriceps"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Glutes"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Calves"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Core"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.PersonalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BestSetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BestSetReps")
                        .HasColumnType("integer");

                    b.Property<decimal>("BestSetWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("MaxWeightDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId", "ExerciseId")
                        .IsUnique();

                    b.ToTable("PersonalRecords");
                });

            modelBuilder.Entity("GymCoach.Api.Models.ProgressionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("FailureThreshold")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxReps")
                        .HasColumnType("integer");

                    b.Property<int>("MinReps")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepIncrement")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightIncrement")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ProgressionRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FailureThreshold = 2,
                            IsDefault = true,
                            MaxReps = 15,
                            MinReps = 8,
                            Name = "Standard Progression",
                            RepIncrement = 1,
                            WeightIncrement = 2.5m
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.RepScheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Configuration")
                        .HasColumnType("text");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxReps")
                        .HasColumnType("integer");

                    b.Property<int?>("MinReps")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetSets")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RepSchemes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSystem = true,
                            MaxReps = 3,
                            MinReps = 1,
                            Name = "Power",
                            RestSeconds = 180,
                            TargetSets = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            IsSystem = true,
                            MaxReps = 6,
                            MinReps = 4,
                            Name = "Strength",
                            RestSeconds = 150,
                            TargetSets = 4,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            IsSystem = true,
                            MaxReps = 12,
                            MinReps = 8,
                            Name = "Hypertrophy",
                            RestSeconds = 90,
                            TargetSets = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            IsSystem = true,
                            MaxReps = 20,
                            MinReps = 15,
                            Name = "Muscular Endurance",
                            RestSeconds = 60,
                            TargetSets = 3,
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            IsSystem = true,
                            MaxReps = 50,
                            MinReps = 20,
                            Name = "Cardio/HIIT",
                            RestSeconds = 30,
                            TargetSets = 2,
                            Type = 5
                        },
                        new
                        {
                            Id = 6,
                            DurationSeconds = 60,
                            IsSystem = true,
                            Name = "EMOM",
                            TargetSets = 10,
                            Type = 100
                        },
                        new
                        {
                            Id = 7,
                            DurationSeconds = 60,
                            IsSystem = true,
                            Name = "AMRAP",
                            TargetSets = 1,
                            Type = 101
                        },
                        new
                        {
                            Id = 8,
                            DurationSeconds = 30,
                            IsSystem = true,
                            Name = "Timed Set",
                            RestSeconds = 60,
                            TargetSets = 3,
                            Type = 102
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.SupersetTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAntagonist")
                        .HasColumnType("boolean");

                    b.Property<int>("MuscleGroupAId")
                        .HasColumnType("integer");

                    b.Property<int>("MuscleGroupBId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupAId");

                    b.HasIndex("MuscleGroupBId");

                    b.ToTable("SupersetTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAntagonist = true,
                            MuscleGroupAId = 1,
                            MuscleGroupBId = 2,
                            Name = "Chest + Back"
                        },
                        new
                        {
                            Id = 2,
                            IsAntagonist = true,
                            MuscleGroupAId = 4,
                            MuscleGroupBId = 5,
                            Name = "Biceps + Triceps"
                        },
                        new
                        {
                            Id = 3,
                            IsAntagonist = true,
                            MuscleGroupAId = 6,
                            MuscleGroupBId = 7,
                            Name = "Quads + Hamstrings"
                        },
                        new
                        {
                            Id = 4,
                            IsAntagonist = true,
                            MuscleGroupAId = 3,
                            MuscleGroupBId = 2,
                            Name = "Shoulders + Back"
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveWorkoutPlanId")
                        .HasColumnType("integer");

                    b.Property<string>("AppleId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppleId")
                        .IsUnique()
                        .HasFilter("\"AppleId\" IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("\"GoogleId\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserEquipment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("UserEquipment");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("SupersetGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("SupersetOrder")
                        .HasColumnType("integer");

                    b.Property<int>("UserWorkoutDayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserWorkoutDayId");

                    b.ToTable("UserExerciseLogs");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserSuperset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseLogAId")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseLogBId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseLogAId");

                    b.HasIndex("ExerciseLogBId");

                    b.ToTable("UserSupersets");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserWorkoutDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<int>("DayTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserWorkoutPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutDayTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserWorkoutPlanId");

                    b.HasIndex("WorkoutDayTemplateId");

                    b.ToTable("UserWorkoutDays");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserWorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("UserWorkoutPlans");
                });

            modelBuilder.Entity("GymCoach.Api.Models.WorkoutDayTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkoutTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("WorkoutDayTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayNumber = 1,
                            Name = "Full Body A",
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayNumber = 2,
                            Name = "Full Body B",
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayNumber = 3,
                            Name = "Full Body C",
                            WorkoutTemplateId = 1
                        },
                        new
                        {
                            Id = 4,
                            DayNumber = 1,
                            Name = "Push",
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 5,
                            DayNumber = 2,
                            Name = "Pull",
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 6,
                            DayNumber = 3,
                            Name = "Legs",
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 7,
                            DayNumber = 4,
                            Name = "Push",
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 8,
                            DayNumber = 5,
                            Name = "Pull",
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 9,
                            DayNumber = 6,
                            Name = "Legs",
                            WorkoutTemplateId = 2
                        },
                        new
                        {
                            Id = 10,
                            DayNumber = 1,
                            Name = "Upper A",
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 11,
                            DayNumber = 2,
                            Name = "Lower A",
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 12,
                            DayNumber = 3,
                            Name = "Upper B",
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 13,
                            DayNumber = 4,
                            Name = "Lower B",
                            WorkoutTemplateId = 3
                        },
                        new
                        {
                            Id = 14,
                            DayNumber = 1,
                            Name = "Chest + Back",
                            WorkoutTemplateId = 4
                        },
                        new
                        {
                            Id = 15,
                            DayNumber = 2,
                            Name = "Arms (Bi + Tri)",
                            WorkoutTemplateId = 4
                        },
                        new
                        {
                            Id = 16,
                            DayNumber = 3,
                            Name = "Legs (Quads + Hams)",
                            WorkoutTemplateId = 4
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.WorkoutDayTemplateMuscle", b =>
                {
                    b.Property<int>("WorkoutDayTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseCount")
                        .HasColumnType("integer");

                    b.HasKey("WorkoutDayTemplateId", "MuscleGroupId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("WorkoutDayTemplateMuscle");

                    b.HasData(
                        new
                        {
                            WorkoutDayTemplateId = 1,
                            MuscleGroupId = 1,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 1,
                            MuscleGroupId = 2,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 1,
                            MuscleGroupId = 3,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 1,
                            MuscleGroupId = 6,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 1,
                            MuscleGroupId = 10,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 2,
                            MuscleGroupId = 1,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 2,
                            MuscleGroupId = 2,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 2,
                            MuscleGroupId = 4,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 2,
                            MuscleGroupId = 7,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 2,
                            MuscleGroupId = 8,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 3,
                            MuscleGroupId = 3,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 3,
                            MuscleGroupId = 5,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 3,
                            MuscleGroupId = 2,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 3,
                            MuscleGroupId = 6,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 3,
                            MuscleGroupId = 9,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 4,
                            MuscleGroupId = 1,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 4,
                            MuscleGroupId = 3,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 4,
                            MuscleGroupId = 5,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 7,
                            MuscleGroupId = 1,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 7,
                            MuscleGroupId = 3,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 7,
                            MuscleGroupId = 5,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 5,
                            MuscleGroupId = 2,
                            ExerciseCount = 3
                        },
                        new
                        {
                            WorkoutDayTemplateId = 5,
                            MuscleGroupId = 4,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 8,
                            MuscleGroupId = 2,
                            ExerciseCount = 3
                        },
                        new
                        {
                            WorkoutDayTemplateId = 8,
                            MuscleGroupId = 4,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 6,
                            MuscleGroupId = 6,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 6,
                            MuscleGroupId = 7,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 6,
                            MuscleGroupId = 8,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 6,
                            MuscleGroupId = 9,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 9,
                            MuscleGroupId = 6,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 9,
                            MuscleGroupId = 7,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 9,
                            MuscleGroupId = 8,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 9,
                            MuscleGroupId = 9,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 10,
                            MuscleGroupId = 1,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 10,
                            MuscleGroupId = 2,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 10,
                            MuscleGroupId = 3,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 10,
                            MuscleGroupId = 4,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 10,
                            MuscleGroupId = 5,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 11,
                            MuscleGroupId = 6,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 11,
                            MuscleGroupId = 7,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 11,
                            MuscleGroupId = 8,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 11,
                            MuscleGroupId = 9,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 11,
                            MuscleGroupId = 10,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 12,
                            MuscleGroupId = 1,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 12,
                            MuscleGroupId = 2,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 12,
                            MuscleGroupId = 3,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 12,
                            MuscleGroupId = 4,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 12,
                            MuscleGroupId = 5,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 13,
                            MuscleGroupId = 6,
                            ExerciseCount = 2
                        },
                        new
                        {
                            WorkoutDayTemplateId = 13,
                            MuscleGroupId = 7,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 13,
                            MuscleGroupId = 8,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 13,
                            MuscleGroupId = 9,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 13,
                            MuscleGroupId = 10,
                            ExerciseCount = 1
                        },
                        new
                        {
                            WorkoutDayTemplateId = 14,
                            MuscleGroupId = 1,
                            ExerciseCount = 3
                        },
                        new
                        {
                            WorkoutDayTemplateId = 14,
                            MuscleGroupId = 2,
                            ExerciseCount = 3
                        },
                        new
                        {
                            WorkoutDayTemplateId = 15,
                            MuscleGroupId = 4,
                            ExerciseCount = 3
                        },
                        new
                        {
                            WorkoutDayTemplateId = 15,
                            MuscleGroupId = 5,
                            ExerciseCount = 3
                        },
                        new
                        {
                            WorkoutDayTemplateId = 16,
                            MuscleGroupId = 6,
                            ExerciseCount = 3
                        },
                        new
                        {
                            WorkoutDayTemplateId = 16,
                            MuscleGroupId = 7,
                            ExerciseCount = 3
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.WorkoutTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasSupersets")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A complete full body workout, 3 days per week. Perfect for beginners.",
                            HasSupersets = false,
                            IsPremium = false,
                            Name = "Full Body 3-Day"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic 6-day split targeting each muscle group twice per week.",
                            HasSupersets = false,
                            IsPremium = true,
                            Name = "Push/Pull/Legs"
                        },
                        new
                        {
                            Id = 3,
                            Description = "4-day split alternating between upper and lower body.",
                            HasSupersets = false,
                            IsPremium = true,
                            Name = "Upper/Lower Split"
                        },
                        new
                        {
                            Id = 4,
                            Description = "High-intensity 3-day program with antagonist supersets for efficient workouts.",
                            HasSupersets = true,
                            IsPremium = true,
                            Name = "Superset Training"
                        });
                });

            modelBuilder.Entity("GymCoach.Api.Models.Exercise", b =>
                {
                    b.HasOne("GymCoach.Api.Models.MuscleGroup", "PrimaryMuscleGroup")
                        .WithMany("PrimaryExercises")
                        .HasForeignKey("PrimaryMuscleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimaryMuscleGroup");
                });

            modelBuilder.Entity("GymCoach.Api.Models.ExerciseEquipment", b =>
                {
                    b.HasOne("GymCoach.Api.Models.Equipment", "Equipment")
                        .WithMany("ExerciseEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCoach.Api.Models.Exercise", "Exercise")
                        .WithMany("RequiredEquipment")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GymCoach.Api.Models.ExerciseSecondaryMuscle", b =>
                {
                    b.HasOne("GymCoach.Api.Models.Exercise", "Exercise")
                        .WithMany("SecondaryMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCoach.Api.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("SecondaryExercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("GymCoach.Api.Models.ExerciseSet", b =>
                {
                    b.HasOne("GymCoach.Api.Models.RepScheme", "RepScheme")
                        .WithMany()
                        .HasForeignKey("RepSchemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GymCoach.Api.Models.UserExerciseLog", "UserExerciseLog")
                        .WithMany("Sets")
                        .HasForeignKey("UserExerciseLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepScheme");

                    b.Navigation("UserExerciseLog");
                });

            modelBuilder.Entity("GymCoach.Api.Models.PersonalRecord", b =>
                {
                    b.HasOne("GymCoach.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GymCoach.Api.Models.ProgressionRule", b =>
                {
                    b.HasOne("GymCoach.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GymCoach.Api.Models.RepScheme", b =>
                {
                    b.HasOne("GymCoach.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymCoach.Api.Models.SupersetTemplate", b =>
                {
                    b.HasOne("GymCoach.Api.Models.MuscleGroup", "MuscleGroupA")
                        .WithMany()
                        .HasForeignKey("MuscleGroupAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymCoach.Api.Models.MuscleGroup", "MuscleGroupB")
                        .WithMany()
                        .HasForeignKey("MuscleGroupBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MuscleGroupA");

                    b.Navigation("MuscleGroupB");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserEquipment", b =>
                {
                    b.HasOne("GymCoach.Api.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCoach.Api.Models.User", "User")
                        .WithMany("OwnedEquipment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserExerciseLog", b =>
                {
                    b.HasOne("GymCoach.Api.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCoach.Api.Models.UserWorkoutDay", "UserWorkoutDay")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("UserWorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("UserWorkoutDay");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserSuperset", b =>
                {
                    b.HasOne("GymCoach.Api.Models.UserExerciseLog", "ExerciseLogA")
                        .WithMany()
                        .HasForeignKey("ExerciseLogAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCoach.Api.Models.UserExerciseLog", "ExerciseLogB")
                        .WithMany()
                        .HasForeignKey("ExerciseLogBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseLogA");

                    b.Navigation("ExerciseLogB");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserWorkoutDay", b =>
                {
                    b.HasOne("GymCoach.Api.Models.UserWorkoutPlan", "UserWorkoutPlan")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("UserWorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCoach.Api.Models.WorkoutDayTemplate", "WorkoutDayTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutDayTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserWorkoutPlan");

                    b.Navigation("WorkoutDayTemplate");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserWorkoutPlan", b =>
                {
                    b.HasOne("GymCoach.Api.Models.User", "User")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCoach.Api.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("GymCoach.Api.Models.WorkoutDayTemplate", b =>
                {
                    b.HasOne("GymCoach.Api.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("DayTemplates")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("GymCoach.Api.Models.WorkoutDayTemplateMuscle", b =>
                {
                    b.HasOne("GymCoach.Api.Models.MuscleGroup", "MuscleGroup")
                        .WithMany()
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymCoach.Api.Models.WorkoutDayTemplate", "WorkoutDayTemplate")
                        .WithMany("TargetMuscles")
                        .HasForeignKey("WorkoutDayTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");

                    b.Navigation("WorkoutDayTemplate");
                });

            modelBuilder.Entity("GymCoach.Api.Models.Equipment", b =>
                {
                    b.Navigation("ExerciseEquipments");
                });

            modelBuilder.Entity("GymCoach.Api.Models.Exercise", b =>
                {
                    b.Navigation("RequiredEquipment");

                    b.Navigation("SecondaryMuscles");
                });

            modelBuilder.Entity("GymCoach.Api.Models.MuscleGroup", b =>
                {
                    b.Navigation("PrimaryExercises");

                    b.Navigation("SecondaryExercises");
                });

            modelBuilder.Entity("GymCoach.Api.Models.User", b =>
                {
                    b.Navigation("OwnedEquipment");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserExerciseLog", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserWorkoutDay", b =>
                {
                    b.Navigation("ExerciseLogs");
                });

            modelBuilder.Entity("GymCoach.Api.Models.UserWorkoutPlan", b =>
                {
                    b.Navigation("WorkoutDays");
                });

            modelBuilder.Entity("GymCoach.Api.Models.WorkoutDayTemplate", b =>
                {
                    b.Navigation("TargetMuscles");
                });

            modelBuilder.Entity("GymCoach.Api.Models.WorkoutTemplate", b =>
                {
                    b.Navigation("DayTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
